services:
  villas-node:
    image: registry.git.rwth-aachen.de/acs/public/villas/node:latest
    container_name: villas-node
    network_mode: host
    privileged: true
    volumes:
      - ./config:/configs:ro
    command: ["node", "/configs/hils.conf"]
    restart: unless-stopped
